name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        ubuntu-version: [ubuntu-18.04, ubuntu-latest]
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.ubuntu-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
    - name: Test cli benchmark
      run: node bin/tickettagger.js benchmark trivial balanced unbalanced --minCount 50
