# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        ubuntu-version: [ubuntu-18.04, ubuntu-latest]
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.ubuntu-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
    - name: Lint
      run: npm run lint
